/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package spigot.server;

import org.bukkit.ChatColor;
import org.bukkit.command.Command;
import org.bukkit.command.CommandSender;
import org.bukkit.entity.Player;
import org.bukkit.plugin.PluginManager;
import org.bukkit.plugin.java.JavaPlugin;

import spigot.server.commands.ClumpsCommands;
import spigot.server.mobs.Clumps;


public class PluginApp extends JavaPlugin {
    
    @Override
    public void onEnable() {
    	PluginManager pm = this.getServer().getPluginManager();
    	pm.registerEvents(new Clumps(this), this);
    	
    	getCommand("clumps").setExecutor(new ClumpsCommands());
    }
    
    @Override
    public void onDisable() {
    	
    }
    
    @Override
    public boolean onCommand(CommandSender sender, Command cmd, String label, String[] args) {
    	if(label.equalsIgnoreCase("mob")) {
    		if(sender instanceof Player) {
    			
    			
    		} else {
    			
    			
    		}
    	}
    	
    	return true;
    }
    
}
