/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package spigot.server;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class PluginAppTest {
    @Test void someLibraryMethodReturnsTrue() {
        
        assertTrue(true, "someLibraryMethod should return 'true'");
    }
}
